Repository depromeet/toks-api, pull requests merged in 2022-12, with the labels that each got.

#33 user_quiz_history 에 quiz_id 컬럼 추가
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/UserQuizHistory.java
  flyway/src/main/resources/db/migration/schema/V1.8__alterTableUserQuizHIstory.sql
Labels: enhancement

#36 #35 순위 관련 API
  api/src/main/java/com/tdns/toks/api/domain/quizrank/controller/QuizRankController.java
  api/src/main/java/com/tdns/toks/api/domain/quizrank/model/dto/QuizRankApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quizrank/service/QuizRankApiService.java
  api/src/main/java/com/tdns/toks/api/domain/user/model/dto/UserApiDTO.java
  api/src/main/resources/application-dev.yml
  core/src/main/java/com/tdns/toks/core/domain/quizrank/model/dto/QuizRankDTO.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/model/entity/QuizRank.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/repository/CustomQuizRankRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/repository/CustomQuizRankRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/repository/QuizRankRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/service/QuizRankService.java
  core/src/main/java/com/tdns/toks/core/domain/study/service/StudyService.java
  flyway/src/main/resources/db/migration/schema/V1.9__alterTableQuizRank.sql
Labels: enhancement

#46 #45 cors allowOrigins 추가(임시)
  core/src/main/java/com/tdns/toks/core/config/security/AuthSecurityConfig.java
Labels: bug

#42 #34 답변 다건 조회
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/UserQuizHistoryController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/UserQuizHistoryApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/UserQuizHistoryApiService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/dto/UserQuizHistoryDto.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/Quiz.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/UserQuizHistoryCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/UserQuizHistoryCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/UserQuizHistoryRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/UserQuizHistoryService.java
Labels: enhancement

#37 #34 답변 생성 및 답변 좋아요 API
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizLikeController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizReplyHistoryController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizLikeApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizReplyHistoryApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/mapper/QuizLikeMapper.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/mapper/QuizReplyHistoryMapper.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizLikeApiService.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizReplyHistoryApiService.java
  core/src/main/java/com/tdns/toks/core/common/exception/ApplicationErrorType.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/dto/QuizReplyHistoryDto.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/Quiz.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/QuizLike.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/QuizReplyHistory.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizLikeCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizLikeCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizLikeRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizReplyHistoryCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizReplyHistoryCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizReplyReplyHistoryRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizLikeService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizReplyHistoryService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizService.java
  flyway/src/main/resources/db/migration/schema/V1.10__alterTableQuizLike.sql
  flyway/src/main/resources/db/migration/schema/V1.11__alterRelatedTableUserQuizHIstory.sql
Labels: enhancement

#43 #41 퀴즈 테이블 변경
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/Quiz.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/StringArrayConverter.java
  flyway/src/main/resources/db/migration/schema/V1.12__alterTableQuiz.sql
Labels: enhancement

#51 dev 환경 db 정보 변경
  api/src/main/resources/application-dev.yml
  flyway/src/main/resources/application-dev.yml
Labels: bug

#48 #32 퀴즈 다건 조회 API
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizApiService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/type/QuizStatusType.java
  core/src/main/java/com/tdns/toks/core/domain/user/model/dto/UserSimpleByQuizIdDTO.java
  core/src/main/java/com/tdns/toks/core/domain/user/model/dto/UserSimpleDTO.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserRepository.java
  core/src/main/java/com/tdns/toks/core/domain/user/service/UserService.java
Labels: enhancement

#47 #32 퀴즈 단건 조회 API
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizLikeApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizReplyHistoryApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizApiService.java
  api/src/main/java/com/tdns/toks/api/domain/quizrank/model/dto/QuizRankApiDTO.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/dto/QuizReplyHistoryDto.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/dto/QuizSimpleDTO.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizReplyHistoryCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/type/QuizStatusType.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/model/dto/QuizRankDTO.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/repository/CustomQuizRankRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/user/model/dto/UserSimpleByQuizIdDTO.java
  core/src/main/java/com/tdns/toks/core/domain/user/model/dto/UserSimpleDTO.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserRepository.java
  core/src/main/java/com/tdns/toks/core/domain/user/service/UserService.java
Labels: enhancement

#52 #50 Flyway 빌드 실패 버그 수정
  flyway/build.gradle
Labels: bug

#66 #65 request host에 맞춘 response
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
  api/src/main/resources/application-prod.yml
  core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2SuccessHandler.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/TagRepository.java
  core/src/main/java/com/tdns/toks/core/domain/study/service/StudyService.java
Labels: enhancement

#68 #67 요청별 redirect 수정
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
  api/src/main/resources/application-prod.yml
  api/src/main/resources/application.yml
  core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2SuccessHandler.java
Labels: bug

#69 :bug: request body 추가
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizLikeController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizReplyHistoryController.java
  api/src/main/java/com/tdns/toks/api/domain/study/controller/StudyController.java
  api/src/main/resources/application.yml
Labels: bug

#64 #10 요청 / 응답 로깅
  api/src/main/java/com/tdns/toks/api/config/ServletConfig.java
  api/src/main/java/com/tdns/toks/api/domain/quizrank/controller/QuizRankController.java
  api/src/main/java/com/tdns/toks/api/filter/LoggingFilter.java
  core/src/main/java/com/tdns/toks/core/config/security/AuthSecurityConfig.java
Labels: enhancement

#72 스터디 생성 오류 대응
  api/src/main/java/com/tdns/toks/api/config/OpenApiConfig.java
  api/src/main/java/com/tdns/toks/api/domain/study/model/dto/StudyApiDTO.java
Labels: bug

#74 ElastiCache 변경
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
  api/src/main/resources/application.yml
Labels: bug

#62 #32 퀴즈 생성 API
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/mapper/QuizMapper.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizApiService.java
  api/src/main/resources/application.yml
  core/src/main/java/com/tdns/toks/core/common/security/LoginUserAuditorAware.java
  core/src/main/java/com/tdns/toks/core/common/service/S3UploadService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/Quiz.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/QuizLike.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/QuizReplyHistory.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizService.java
  flyway/src/main/resources/db/migration/schema/V1.13__alterAnswerColumn.sql
Labels: enhancement

#77 #63 순위 관련 API 필드 추가
  core/src/main/java/com/tdns/toks/core/domain/quizrank/model/dto/QuizRankDTO.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/repository/CustomQuizRankRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/service/QuizRankService.java
Labels: enhancement

#83 :bug: 정렬 순서 버그 수정
  core/src/main/java/com/tdns/toks/core/domain/quizrank/repository/CustomQuizRankRepositoryImpl.java
Labels: bug

#44 #31 사용자의 진행중인 스터디 목록 조회 (다건조회)
  api/src/main/java/com/tdns/toks/api/domain/study/controller/StudyController.java
  api/src/main/java/com/tdns/toks/api/domain/study/model/dto/StudyApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/study/service/StudyApiService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/dto/QuizDTO.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizReplyHistoryRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizReplyHistoryService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/type/StudyLatestQuizStatus.java
  core/src/main/java/com/tdns/toks/core/domain/study/model/dto/StudyDTO.java
  core/src/main/java/com/tdns/toks/core/domain/study/model/dto/StudyTagsDTO.java
  core/src/main/java/com/tdns/toks/core/domain/study/model/entity/Study.java
  core/src/main/java/com/tdns/toks/core/domain/study/model/entity/StudyUser.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyRepository.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyTagRepository.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyUserRepository.java
  core/src/main/java/com/tdns/toks/core/domain/study/service/StudyService.java
  core/src/main/java/com/tdns/toks/core/domain/study/service/TagService.java
  core/src/main/java/com/tdns/toks/core/domain/user/service/UserService.java
Labels: enhancement

#61 #54 Study 정보 단건 조회 API
  api/src/main/java/com/tdns/toks/api/domain/study/controller/StudyController.java
  api/src/main/java/com/tdns/toks/api/domain/study/model/dto/StudyApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/study/service/StudyApiService.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyRepository.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyUserRepository.java
  core/src/main/java/com/tdns/toks/core/domain/study/service/StudyService.java
  core/src/main/java/com/tdns/toks/core/domain/study/type/StudyUserStatus.java
  core/src/main/java/com/tdns/toks/core/domain/user/model/dto/UserSimpleDTO.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserRepository.java
Labels: enhancement

#80 #78 똑순위 계산 방식 반영
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizLikeApiService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/Quiz.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/model/entity/QuizRank.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/repository/QuizRankRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quizrank/service/QuizRankService.java
Labels: enhancement

#81 #79 스터디 참여자 테이블 반영
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizApiService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyUserCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyUserCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyUserRepository.java
  core/src/main/java/com/tdns/toks/core/domain/study/service/StudyUserService.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserCustomRepository.java
  core/src/main/java/com/tdns/toks/core/domain/user/repository/UserRepository.java
  core/src/main/java/com/tdns/toks/core/domain/user/service/UserService.java
Labels: bug, enhancement

#86 #85 입장 시 스터디 정보 조회 api
  api/src/main/java/com/tdns/toks/api/domain/study/controller/StudyController.java
  api/src/main/java/com/tdns/toks/api/domain/study/model/dto/StudyApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/study/service/StudyApiService.java
  api/src/main/resources/application.yml
Labels: enhancement
