Repository depromeet/toks-api, pull requests merged in 2023-01, with the labels that each got.

#95 #94 스터디 생성 분기 수정
  core/src/main/java/com/tdns/toks/core/domain/study/type/StudyStatus.java
Labels: bug

#93 퀴즈 조회시, 회차 필드 추가
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/mapper/QuizMapper.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizApiService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/dto/QuizSimpleDTO.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/entity/Quiz.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/type/QuizStatusType.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/type/QuizType.java
  core/src/main/java/com/tdns/toks/core/domain/study/repository/StudyUserCustomRepositoryImpl.java
  core/src/test/java/com/tdns/toks/core/domain/quiz/QuizServiceTest.java
  flyway/src/main/resources/db/migration/schema/V1.16__alterTableQuiz.sql
Labels: enhancement

#100 퀴즈 생성 시, 제한 시간 필드 추가
  api/src/main/java/com/tdns/toks/api/domain/quiz/controller/QuizController.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/dto/QuizApiDTO.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/model/mapper/QuizMapper.java
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizApiService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizReplyHistoryCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizReplyHistoryService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizService.java
Labels: enhancement

#109 퀴즈 생성 및 답변 조회 이슈 해결
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizApiService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/model/dto/QuizReplyHistoryDto.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizReplyHistoryCustomRepositoryImpl.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizRepository.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizReplyHistoryService.java
  core/src/main/java/com/tdns/toks/core/domain/quiz/service/QuizService.java
Labels: bug, enhancement

#112 :bug: value 값 비교
  api/src/main/java/com/tdns/toks/api/domain/quiz/service/QuizApiService.java
Labels: bug

#114 #113 스터디 생성일자 종료일자 정합성
  core/src/main/java/com/tdns/toks/core/domain/study/service/StudyService.java
Labels: bug

#116 Hotfix/quiz reply history sort
  core/src/main/java/com/tdns/toks/core/domain/quiz/repository/QuizReplyHistoryCustomRepositoryImpl.java
Labels: bug
